import { ResQNovaState } from '../types';
import { computeAiFloodPrediction } from './floodPredictionEngine';

export function getInitialResQNovaState(): ResQNovaState {
  const now = new Date().toISOString();
  const initialSosTime = new Date(Date.now() - 15 * 60 * 1000).toISOString();

  const defaultPrediction = computeAiFloodPrediction({
    inflowCusecs: 510000,
    rainfallMm: 185,
    soilMoisturePct: 92,
    gatesOpen: 68,
  });

  return {
    users: [
      {
        id: 'usr-admin-1',
        email: 'admin@resqnova.gov.in',
        full_name: 'Dr. K. Swaminathan (Collector & DM)',
        role: 'admin',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
      {
        id: 'usr-citizen-1',
        email: 'ramesh.p@gmail.com',
        full_name: 'P. Ramesh',
        phone: '+91 98480 23114',
        role: 'citizen',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
      {
        id: 'usr-rescue-1',
        email: 'ndrf.alpha@resqnova.gov.in',
        full_name: 'Inspector Vikram Singh (NDRF Boat Squad Alpha)',
        phone: '+91 94401 88722',
        role: 'rescue',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
      {
        id: 'usr-ambulance-1',
        email: 'medic.108@resqnova.gov.in',
        full_name: 'S. Koteswara Rao (108 ALS Unit 101)',
        phone: '+91 98492 10801',
        role: 'ambulance',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
      {
        id: 'usr-shelter-1',
        email: 'igmc.shelter@resqnova.gov.in',
        full_name: 'M. Anitha (IGMC Stadium Relief Officer)',
        phone: '+91 866 2471001',
        role: 'shelter',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
      {
        id: 'usr-hospital-1',
        email: 'ggh.er@resqnova.gov.in',
        full_name: 'Dr. V. Prasad (GGH Superintendent)',
        phone: '+91 866 2575555',
        role: 'hospital',
        district: 'NTR District, Vijayawada',
        created_at: now,
      },
    ],
    shelters: [
      {
        id: 'shl-1',
        shelter_name: 'IGMC Stadium Emergency Camp',
        district: 'NTR',
        latitude: 16.5055,
        longitude: 80.6508,
        capacity: 1200,
        available_capacity: 680,
        occupancy: 520,
        food_stock: 'Adequate',
        water_stock: 'Adequate',
        power_backup: true,
        contact_number: '+91 866 2471001',
        address: 'MG Road, Labbipet, Vijayawada',
        updated_at: now,
      },
      {
        id: 'shl-2',
        shelter_name: 'Siddhartha Medical College Complex',
        district: 'NTR',
        latitude: 16.5012,
        longitude: 80.6725,
        capacity: 800,
        available_capacity: 420,
        occupancy: 380,
        food_stock: 'Abundant',
        water_stock: 'Adequate',
        power_backup: true,
        contact_number: '+91 866 2473456',
        address: 'Gunadala, Vijayawada',
        updated_at: now,
      },
      {
        id: 'shl-3',
        shelter_name: 'Bishop Azaraiah Girls High School Relief Hub',
        district: 'NTR',
        latitude: 16.5165,
        longitude: 80.6272,
        capacity: 650,
        available_capacity: 310,
        occupancy: 340,
        food_stock: 'Adequate',
        water_stock: 'Low',
        power_backup: true,
        contact_number: '+91 866 2420999',
        address: 'Governorpet, Vijayawada',
        updated_at: now,
      },
      {
        id: 'shl-4',
        shelter_name: 'Andhra Loyola College Gymnasium Shelter',
        district: 'NTR',
        latitude: 16.5078,
        longitude: 80.6621,
        capacity: 1000,
        available_capacity: 750,
        occupancy: 250,
        food_stock: 'Abundant',
        water_stock: 'Abundant',
        power_backup: true,
        contact_number: '+91 866 2476082',
        address: 'Loyola Gardens, Vijayawada',
        updated_at: now,
      },
    ],
    hospitals: [
      {
        id: 'hosp-1',
        hospital_name: 'Government General Hospital (GGH) Vijayawada',
        district: 'NTR',
        latitude: 16.5122,
        longitude: 80.6385,
        total_beds: 450,
        available_beds: 85,
        emergency_capacity: 40,
        icu_beds: 24,
        ambulances_available: 4,
        contact_number: '+91 866 2575555',
        updated_at: now,
      },
      {
        id: 'hosp-2',
        hospital_name: 'Manipal Hospital Tadepalli Trauma Center',
        district: 'NTR / Guntur Border',
        latitude: 16.4835,
        longitude: 80.6152,
        total_beds: 300,
        available_beds: 62,
        emergency_capacity: 30,
        icu_beds: 18,
        ambulances_available: 3,
        contact_number: '+91 866 6499999',
        updated_at: now,
      },
      {
        id: 'hosp-3',
        hospital_name: 'Andhra Hospitals Emergency Wing Governorpet',
        district: 'NTR',
        latitude: 16.5145,
        longitude: 80.6322,
        total_beds: 220,
        available_beds: 45,
        emergency_capacity: 20,
        icu_beds: 12,
        ambulances_available: 2,
        contact_number: '+91 866 2438888',
        updated_at: now,
      },
    ],
    rescue_teams: [
      {
        id: 'tm-1',
        team_name: 'NDRF Boat Squad Alpha',
        leader: 'Insp. Vikram Singh',
        latitude: 16.5028,
        longitude: 80.6355,
        status: 'deployed',
        personnel: 8,
        equipment: 'Inflatable Zodiac Boats (2), OBMs, Life Jackets, Satellite Comms',
        deployment_zone: 'Krishna Riverfront / Krishna Lanka',
        assigned_request_id: 'req-vja-001',
        updated_at: now,
      },
      {
        id: 'tm-2',
        team_name: 'SDRF Rapid Water Extraction Unit 2',
        leader: 'Sub-Insp. M. Satyanarayana',
        latitude: 16.5215,
        longitude: 80.6125,
        status: 'available',
        personnel: 6,
        equipment: 'FRP Flood Boats, Line Throwers, First Aid Trauma Kit',
        deployment_zone: 'Bhavanipuram / Gollapudi',
        updated_at: now,
      },
      {
        id: 'tm-3',
        team_name: 'AP Fire & Disaster Response Squad 4',
        leader: 'Station Officer R. Prasad',
        latitude: 16.5162,
        longitude: 80.6482,
        status: 'available',
        personnel: 7,
        equipment: 'High-Axle 4x4 Rescue Truck, Chainsaws, Mud Pumps',
        deployment_zone: 'Governorpet / Moghalrajpuram',
        updated_at: now,
      },
      {
        id: 'tm-4',
        team_name: 'Marine Police Coastal Rescue 1',
        leader: 'SI K. Srinivasa Rao',
        latitude: 16.4952,
        longitude: 80.6225,
        status: 'available',
        personnel: 6,
        equipment: 'Rigid Inflatable Hull Boat, Diving Gear, Thermal Scanners',
        deployment_zone: 'Prakasam Barrage Downstream',
        updated_at: now,
      },
    ],
    ambulances: [
      {
        id: 'amb-1',
        vehicle_code: 'AP-108-ALS-101',
        driver_name: 'S. Koteswara Rao',
        phone: '+91 98492 10801',
        latitude: 16.5085,
        longitude: 80.6412,
        status: 'deployed',
        crew_size: 2,
        fuel: 92,
        deployment_zone: 'Kanaka Durga Varadhi South Approach',
        assigned_request_id: 'req-vja-001',
        updated_at: now,
      },
      {
        id: 'amb-2',
        vehicle_code: 'AP-108-ALS-104',
        driver_name: 'G. Venkatesh',
        phone: '+91 98492 10804',
        latitude: 16.5015,
        longitude: 80.6585,
        status: 'available',
        crew_size: 2,
        fuel: 85,
        deployment_zone: 'Benz Circle Sector',
        updated_at: now,
      },
      {
        id: 'amb-3',
        vehicle_code: 'AP-108-BLS-202',
        driver_name: 'D. Naga Raju',
        phone: '+91 98492 10822',
        latitude: 16.5245,
        longitude: 80.6095,
        status: 'available',
        crew_size: 2,
        fuel: 95,
        deployment_zone: 'Bhavanipuram Overpass',
        updated_at: now,
      },
    ],
    roads: [
      {
        id: 'rd-1',
        road_name: 'Prakasam Barrage Direct Access Road',
        district: 'NTR',
        status: 'blocked',
        blocked_reason: 'Krishna River overtopping with 2.8m violent flood current',
        start_lat: 16.5075,
        start_lng: 80.6185,
        end_lat: 16.4982,
        end_lng: 80.6122,
        travel_time: 25,
        risk_score: 96,
        updated_at: now,
      },
      {
        id: 'rd-2',
        road_name: 'Krishna Lanka River Bund Road',
        district: 'NTR',
        status: 'flooded',
        blocked_reason: 'Breach in bund sector 3; 1.8m stagnant water',
        start_lat: 16.4995,
        start_lng: 80.6355,
        end_lat: 16.4925,
        end_lng: 80.6485,
        travel_time: 30,
        risk_score: 92,
        updated_at: now,
      },
      {
        id: 'rd-3',
        road_name: 'MG Road (Mahatma Gandhi Road) Main Artery',
        district: 'NTR',
        status: 'open',
        start_lat: 16.5135,
        start_lng: 80.6312,
        end_lat: 16.5015,
        end_lng: 80.6585,
        travel_time: 11,
        risk_score: 15,
        updated_at: now,
      },
      {
        id: 'rd-4',
        road_name: 'NH-16 Kanaka Durga Flyover / Elevated Highway',
        district: 'NTR',
        status: 'open',
        start_lat: 16.5215,
        start_lng: 80.6125,
        end_lat: 16.5085,
        end_lng: 80.6395,
        travel_time: 7,
        risk_score: 10,
        updated_at: now,
      },
      {
        id: 'rd-5',
        road_name: 'Bhavanipuram Canal Side Road',
        district: 'NTR',
        status: 'flooded',
        blocked_reason: 'Canal overflow submerged road up to 1.2m depth',
        start_lat: 16.5185,
        start_lng: 80.6055,
        end_lat: 16.5255,
        end_lng: 80.6195,
        travel_time: 20,
        risk_score: 84,
        updated_at: now,
      },
    ],
    risk_zones: [
      {
        id: 'zone-1',
        zone_name: 'Zone A: Krishna Lanka Riverfront Sector',
        district: 'NTR',
        risk_level: 'Critical',
        risk_score: 95,
        water_level_m: 3.8,
        polygon: [
          [16.5045, 80.6285],
          [16.5015, 80.6425],
          [16.4912, 80.6465],
          [16.4885, 80.6325],
          [16.4985, 80.6245],
        ],
      },
      {
        id: 'zone-2',
        zone_name: 'Zone B: Bhavanipuram Lowland Spillway',
        district: 'NTR',
        risk_level: 'High',
        risk_score: 82,
        water_level_m: 2.3,
        polygon: [
          [16.5295, 80.6015],
          [16.5325, 80.6185],
          [16.5195, 80.6225],
          [16.5145, 80.6055],
        ],
      },
      {
        id: 'zone-3',
        zone_name: 'Zone C: Ramavarappadu Inundation Pocket',
        district: 'NTR',
        risk_level: 'High',
        risk_score: 76,
        water_level_m: 1.9,
        polygon: [
          [16.5225, 80.6715],
          [16.5295, 80.6865],
          [16.5165, 80.6912],
          [16.5085, 80.6755],
        ],
      },
    ],
    citizen_requests: [
      {
        id: 'req-vja-001',
        request_id: 'REQ-VJA-8041',
        citizen_name: 'P. Ramesh',
        citizen_phone: '+91 98480 23114',
        latitude: 16.4982,
        longitude: 80.6385,
        address_hint: 'House #4-12, Behind Bund Police Outpost, Krishna Lanka',
        people_count: 5,
        children_count: 2,
        elderly_count: 1,
        emergency_type: 'Flood Trapped',
        medical_urgency: 'moderate',
        risk_level: 'Critical',
        risk_score: 94,
        priority_score: 96,
        ai_confidence: 94,
        ai_reason:
          'Water level reached 1st floor balcony. 2 infants and 1 asthmatic elder trapped. Nearest road blocked by 1.8m current.',
        ai_recommendation:
          'Dispatch NDRF inflatable boat squad with ALS ambulance standby at high-elevation Bund access point.',
        ai_stage: 'dispatched',
        status: 'assigned',
        rescue_team_id: 'tm-1',
        ambulance_id: 'amb-1',
        recommended_shelter_id: 'shl-1',
        recommended_hospital_id: 'hosp-1',
        assigned_at: initialSosTime,
        eta: new Date(Date.now() + 12 * 60 * 1000).toISOString(),
        created_at: initialSosTime,
      },
    ],
    rescue_missions: [
      {
        id: 'msn-001',
        request_id: 'req-vja-001',
        rescue_team_id: 'tm-1',
        ambulance_id: 'amb-1',
        latitude: 16.4982,
        longitude: 80.6385,
        mission_status: 'assigned',
        readiness: 'active',
        last_updated: initialSosTime,
        notes: 'Priority evacuation of elderly patient and 2 infants from Krishna Lanka sector.',
      },
    ],
    ai_execution_logs: [
      {
        id: 'log-001',
        request_id: 'req-vja-001',
        step: 'SOS Received',
        status: 'success',
        details: {
          requestId: 'REQ-VJA-8041',
          coords: [16.4982, 80.6385],
          people: 5,
        },
        created_at: initialSosTime,
      },
      {
        id: 'log-002',
        request_id: 'req-vja-001',
        step: 'Context & GIS Layers Loaded',
        status: 'success',
        details: {
          activeZone: 'Zone A: Krishna Lanka Riverfront Sector',
          waterLevel: '3.8m',
          blockedRoads: 2,
        },
        created_at: initialSosTime,
      },
      {
        id: 'log-003',
        request_id: 'req-vja-001',
        step: 'Gemini AI Triage Evaluated',
        status: 'success',
        details: {
          model: 'gemini-3.8-flash',
          priority: 'Critical',
          riskScore: 94,
          dispatchRescue: true,
          dispatchAmbulance: true,
        },
        created_at: initialSosTime,
      },
      {
        id: 'log-004',
        request_id: 'req-vja-001',
        step: 'Resource Dispatch Assigned',
        status: 'success',
        details: {
          rescueTeam: 'NDRF Boat Squad Alpha',
          ambulance: 'AP-108-ALS-101',
          shelter: 'IGMC Stadium Emergency Camp',
        },
        created_at: initialSosTime,
      },
    ],
    latest_ai_flood_prediction: {
      ...defaultPrediction,
      id: 'pred-vja-current',
      predicted_at: now,
      forecast_window_hours: 12,
      predicted_barrage_cusecs: 840000,
      upstream_rainfall_mm_hr: 68,
      soil_moisture_pct: 91,
      flood_crest_eta_hours: 7.5,
      inundation_velocity_mps: 2.3,
      ai_synthesis_summary:
        'Spatio-temporal neural model predicts Krishna river crest at T+7.5h with discharge surging to 8.4 Lakh Cusecs. High inundation risk (Red Area) focused along Krishna Lanka Bund. Quantum QUBO optimizer successfully pre-positioned rescue boats and ALS ambulances on elevated perimeters, cutting emergency latency by 78.4%.',
    },
  };
}
